services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./Backend/.env  # Agrega esta línea para usar el archivo .env
    environment:
      - user=root
      - pass=smb2015
      - host=localhost
      - port=3307
      - db_name=deathnotedb

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smb2015
      MYSQL_DATABASE: deathnotedb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
